#!/bin/bash -

set -o errexit
set -o nounset
set -o pipefail

cert_group=kube-cert
cert_dir=/etc/kubernetes/tls

pem_ca=$cert_dir/ca.pem
pem_ca_key=$cert_dir/ca-key.pem
pem_server=$cert_dir/apiserver.pem
pem_server_key=$cert_dir/apiserver-key.pem
pem_server_csr=$cert_dir/apiserver-csr.pem

pem_admin=$cert_dir/admin.pem
pem_admin_key=$cert_dir/admin-key.pem
pem_admin_csr=$cert_dir/admin-csr.pem

# Make sure cert group exists
[ $(getent group $cert_group) ] || groupadd -r $cert_group

# Generate TLS artifacts
mkdir -p "$cert_dir"
rm -rf "$cert_dir/*"

openssl genrsa -out $pem_ca_key 2048
openssl req -x509 -new -nodes -key $pem_ca_key -days 10000 -out $pem_ca -subj "/CN=kube-ca"

openssl genrsa -out $pem_server_key 2048
openssl req -new -key $pem_server_key -out $pem_server_csr -subj "/CN=__HOSTNAME__" -config openssl.cnf
openssl x509 -req -in $pem_server_csr -CA $pem_ca -CAkey $pem_ca_key -CAcreateserial -out $pem_server -days 365 -extensions v3_req -extfile openssl.cnf

# Make server certs accessible to apiserver.
chgrp $cert_group $pem_ca $pem_ca_key $pem_server $pem_server_key
chmod 600 $pem_ca_key $pem_server_key
chmod 660 $pem_ca $pem_server

# Generate admin
openssl genrsa -out $pem_admin_key 2048
openssl req -new -key $pem_admin_key -out $pem_admin_csr -subj "/CN=kube-admin"
openssl x509 -req -in $pem_admin_csr -CA $pem_ca -CAkey $pem_ca_key -CAcreateserial -out $pem_admin -days 365
